### ISSUE TITLE
Library skips empty cells in the returned data

### ISSUE THREAD

**Issue by siddhant2408** [TheDataShed/xlsxreader#14]
Let's say the excel file contains the following data
```
Email,Name,Age
test@test.com,,18
```
The returned row will only contain
```
Email,Name,Age
test@test.com,18
```

This is an issue as 18 will be under the `Name` header wherein we want empty string under `Name`.

**Comment by dglsparsons** [comment]
Hi, interesting issue - Empty cells do appear to be handled, but it's not immediately obvious how.

The `Cells` contained within a row only shows the populated fields in an Excel spreadsheet, there is no padding of blank Cells (or cells with no content), since the xlsx format distinguishes between a cell that has no content, and a cell that has never had any content. 

The trick, is when iterating over the Cells in a row, is to look at the `Column` value. 

These two definitions may help :- 
```go
type Row struct {
	Error error
	Index int
	Cells []Cell
}

type Cell struct {
	Column string // E.G   A, B, C
	Row    int
	Value  string
}
```

In your example, the data would be presented in the following format: 
```
row := Row{
  Error: nil,
  Index: 2,
  Cells: []Cell{
    {
      Column: "A",
      Row: 2, 
      Value: "test@test.com",
    },
    { 
      Column: "C",
      Row: 2,
      Value: "18",
    },
  }
}
```


Hope this makes sense!

**Comment by siddhant2408** [comment]
Yes, thank you.
